CREATE TABLE dda_product_history (
    holding_company_id INTEGER NOT NULL,
    bank_id INTEGER NOT NULL,
    branch_id INTEGER NOT NULL,
    product_id TEXT NOT NULL,
    old_product_description TEXT,
    old_minimum_opening_deposit INTEGER,
    old_minimum_balance INTEGER,
    old_overdraft_limit INTEGER,
    old_overdraft_fee INTEGER,
    old_apy NUMERIC,
    old_insert_date TEXT,
    old_update_date TEXT,
    old_updated_by TEXT,
    new_product_description TEXT,
    new_minimum_opening_deposit INTEGER,
    new_minimum_balance INTEGER,
    new_overdraft_limit INTEGER,
    new_overdraft_fee INTEGER,
    new_apy NUMERIC,
    new_insert_date TEXT,
    new_update_date TEXT,
    new_updated_by TEXT,
    history_insert_date TEXT DEFAULT CURRENT_TIMESTAMP
);
